npm run start:quick -- alice-abreu --scrappy
npm run start:quick -- anderson-leonardo-oliveira --scrappy
npm run start:quick -- blank --scrappy
npm run start:quick -- claudio-junior --scrappy
npm run start:quick -- demetrius-nunes-alves --scrappy
npm run start:quick -- elitefour --scrappy
npm run start:quick -- fabio-damian --scrappy
npm run start:quick -- felipe-dermann-de-moura --scrappy
npm run start:quick -- gabriel-cunegato --scrappy
npm run start:quick -- gabriel-fazenda --scrappy
npm run start:quick -- gabriel-lanzer-kannenberg --scrappy
npm run start:quick -- gabriel-nunes-da-silva --scrappy
npm run start:quick -- guilherme-rosa-nunes --scrappy
npm run start:quick -- guilherme-schaidhauer-de-castro --scrappy
npm run start:quick -- gustavo-roman-marangon --scrappy
npm run start:quick -- infodump --scrappy
npm run start:quick -- iuri-fontana-de-nardin --scrappy
npm run start:quick -- joao-pedro-da-costa-nunes --scrappy
npm run start:quick -- lucas-reis-nunes --scrappy
npm run start:quick -- luiz-wendt --scrappy
npm run start:quick -- mateus-ribeiro --scrappy
npm run start:quick -- matheus-nunes --scrappy
npm run start:quick -- meetthefakers --scrappy
npm run start:quick -- moises-abraham-assayag-neto-assayag --scrappy
npm run start:quick -- randumb --scrappy
npm run start:quick -- research --scrappy
npm run start:quick -- riann-lauermann-selegar --scrappy
npm run start:quick -- splashbot --scrappy
npm run start:quick -- stabby --scrappy
npm run start:quick -- stonedbirdie --scrappy
npm run start:quick -- tiago-duarte --scrappy
npm run start:quick -- vitor-luis-mauricio-da-silva --scrappy
npm run start:quick -- whynotbaut --scrappy
