npm run start:quick -- alice-abreu --opponent=anderson-leonardo-oliveira --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=claudio-junior --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=demetrius-nunes-alves --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=fabio-damian --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=felipe-dermann-de-moura --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=gabriel-cunegato --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=gabriel-fazenda --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- alice-abreu --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=claudio-junior --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=demetrius-nunes-alves --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=fabio-damian --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=felipe-dermann-de-moura --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=gabriel-cunegato --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=gabriel-fazenda --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- anderson-leonardo-oliveira --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=demetrius-nunes-alves --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=fabio-damian --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=felipe-dermann-de-moura --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=gabriel-cunegato --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=gabriel-fazenda --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- claudio-junior --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=fabio-damian --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=felipe-dermann-de-moura --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=gabriel-cunegato --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=gabriel-fazenda --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- demetrius-nunes-alves --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=felipe-dermann-de-moura --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=gabriel-cunegato --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=gabriel-fazenda --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- fabio-damian --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=gabriel-cunegato --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=gabriel-fazenda --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- felipe-dermann-de-moura --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=gabriel-fazenda --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- gabriel-cunegato --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=gabriel-lanzer-kannenberg --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- gabriel-fazenda --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=gabriel-nunes-da-silva --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- gabriel-lanzer-kannenberg --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=guilherme-rosa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- gabriel-nunes-da-silva --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=guilherme-schaidhauer-de-castro --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- guilherme-rosa-nunes --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=gustavo-roman-marangon --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- guilherme-schaidhauer-de-castro --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=iuri-fontana-de-nardin --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- gustavo-roman-marangon --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=joao-pedro-da-costa-nunes --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- iuri-fontana-de-nardin --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=lucas-reis-nunes --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- joao-pedro-da-costa-nunes --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- lucas-reis-nunes --opponent=luiz-wendt --matches=3 format=randombattle
npm run start:quick -- lucas-reis-nunes --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- lucas-reis-nunes --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- lucas-reis-nunes --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- lucas-reis-nunes --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- lucas-reis-nunes --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- lucas-reis-nunes --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- luiz-wendt --opponent=mateus-ribeiro --matches=3 format=randombattle
npm run start:quick -- luiz-wendt --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- luiz-wendt --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- luiz-wendt --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- luiz-wendt --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- luiz-wendt --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- mateus-ribeiro --opponent=matheus-nunes --matches=3 format=randombattle
npm run start:quick -- mateus-ribeiro --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- mateus-ribeiro --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- mateus-ribeiro --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- mateus-ribeiro --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- matheus-nunes --opponent=moises-abraham-assayag-neto-assayag --matches=3 format=randombattle
npm run start:quick -- matheus-nunes --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- matheus-nunes --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- matheus-nunes --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- moises-abraham-assayag-neto-assayag --opponent=riann-lauermann-selegar --matches=3 format=randombattle
npm run start:quick -- moises-abraham-assayag-neto-assayag --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- moises-abraham-assayag-neto-assayag --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- riann-lauermann-selegar --opponent=tiago-duarte --matches=3 format=randombattle
npm run start:quick -- riann-lauermann-selegar --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle
npm run start:quick -- tiago-duarte --opponent=vitor-luis-mauricio-da-silva --matches=3 format=randombattle


That should be it.
