export default {
  CRAFTYSHIELD: 'craftyshield',
  HEALINGWISH: 'healingwish',
  LIGHTSCREEN: 'lightscreen',
  LUCKYCHANT: 'luckychant',
  LUNARDANCE: 'lunardance',
  MATBLOCK: 'matblock',
  MIST: 'mist',
  QUICKGUARD: 'quickguard',
  REFLECT: 'reflect',
  SAFEGUARD: 'safeguard',
  SPIKES: 'spikes',
  STEALTHROCK: 'stealthrock',
  STICKYWEB: 'stickyweb',
  TAILWIND: 'tailwind',
  TOXICSPIKES: 'toxicspikes',
  WIDEGUARD: 'wideguard',
  WISH: 'Wish',
};
