/**
 * Constants for volatile statuses.
 *
 * @see http://bulbapedia.bulbagarden.net/wiki/Status_condition#Volatile_status
 */
module.exports = {
  AQUARING: 'aquaring',
  ATTRACT: 'attract',
  AUTOTOMIZE: 'autotomize',
  BIDE: 'bide',
  CHARGE: 'charge',
  CONFUSION: 'confusion',
  CURSE: 'curse',
  DESTINYBOND: 'destinybond',
  DISABLE: 'disable',
  ELECTRIFY: 'electrify',
  EMBARGO: 'embargo',
  ENCORE: 'encore',
  ENDURE: 'endure',
  FLINCH: 'flinch',
  FOCUSENERGY: 'focusenergy',
  FOLLOWME: 'followme',
  FORESIGHT: 'foresight',
  GASTROACID: 'gastroacid',
  GRUDGE: 'grudge',
  HEALBLOCK: 'healblock',
  HELPINGHAND: 'helpinghand',
  IMPRISON: 'imprison',
  INGRAIN: 'ingrain',
  KINGSSHIELD: 'kingsshield',
  LEECHSEED: 'leechseed',
  MAGICCOAT: 'magiccoat',
  MAGNETRISE: 'magnetrise',
  MINIMIZE: 'minimize',
  MIRACLEEYE: 'miracleeye',
  NIGHTMARE: 'nightmare',
  PARTIALLYTRAPPED: 'partiallytrapped',
  POWDER: 'powder',
  POWERTRICK: 'powertrick',
  PROTECT: 'protect',
  RAGEPOWDER: 'ragepowder',
  SMACKDOWN: 'smackdown',
  SNATCH: 'snatch',
  SPIKYSHIELD: 'spikyshield',
  STOCKPILE: 'stockpile',
  TAUNT: 'taunt',
  TELEKINESIS: 'telekinesis',
  TORMENT: 'torment',
  TRAPPED: 'trapped',
  WISH: 'wish',
  YAWN: 'yawn'
};
